[build]
  functions = "netlify/functions" # O Netlify vai procurar suas funções aqui
  publish = "." # O Netlify vai publicar os arquivos da pasta raiz (onde está o index.html)

[functions]
  node_bundler = "esbuild" # Ferramenta para otimizar suas funções Node.js